//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager_Back
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int ProjectID { get; set; }
        public int TaskID { get; set; }
        public string PersonID { get; set; }
        public Nullable<System.DateTime> AppointedAt { get; set; }
    }
}
