//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager_Back
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Tasks
    {
        public int Id { get; set; }
        public int Parent { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Title { get; set; }
        public string Description_ { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public Nullable<System.DateTime> ExpectedAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastUpdatedAt { get; set; }
        public string CreatorID { get; set; }
        public int Type_ { get; set; }
        public int Color { get; set; }
        public Nullable<int> Status_ { get; set; }
    
        [IgnoreDataMember]
        public virtual Project Project { get; set; }
    }
}
